twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    form_themes:
        - 'form/form_div_layout.html.twig'
        - 'form/vich_fields.html.twig'

    globals:
        site_name: '%app.site_name%'