vich_uploader:
    db_driver: orm

    mappings:
        article_pdf:
            uri_prefix: /pdf
            upload_destination: '%kernel.project_dir%/public/pdf'
            namer: Vich\UploaderBundle\Naming\Base64Namer
